### ISSUE TITLE
Simply requiring the module generates a `cannot self-register` error

### ISSUE THREAD

**Issue by julienvincent** [JamesBarwell/rpi-gpio.js#30]
I'm running on node 5.x, and just requiring the module generates this error:

```
> require('rpi-gpio')
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:423:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/Users/julienvincent/code/test/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/julienvincent/code/test/node_modules/epoll/epoll.js:1:99)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
>
```

I will attempt to fix this, but so long I'm just letting everyone know. I guess this is caused by epoll? I'm not sure.

**Comment by julienvincent** [comment]
Oops. Sorry this is just as I am running on OSX, epoll was build for linux. Feeling stupid.
